wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.8.5
      5: 0.10.31
      8:
      - 1
      - 3
      - 5
    viz:
      calibration_curve:
        historyFieldSettings:
          key: calibration_curve
          x-axis: _step
        id: wandb/calibration/v1
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
      summary_metrics:
        historyFieldSettings:
          key: summary_metrics
          x-axis: _step
        id: wandb/metrics/v1
